services:
  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - backend
    volumes:
          - ./frontend/:/usr/src/app
          - node_modules:/usr/src/app/node_modules

  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - 44600:8080
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
    environment:
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - JWT_SECRET=$JWT_SECRET

  db:
    container_name: db
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB


volumes:
  node_modules:
  db_data:
