services:
  frontend:
    container_name: frontend
    image: nginx:stable-alpine
    ports:
      - 4200:4200
    depends_on:
      - backend
    volumes:
      - ./frontend/dist/abubakkar-apps/browser:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - 44600:8080
    depends_on:
      - db

  db:
    container_name: db
    build: 
      context: db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB


volumes:
  node_modules:
  db_data:
