services:
  frontend:
    container_name: frontend
    image: nginx:stable-alpine
    ports:
      - 4200:4200
    depends_on:
      - backend
    volumes:
      - ./frontend/browser:/usr/share/nginx/html:ro,z
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    container_name: backend
    image: eclipse-temurin:21-jdk-alpine
    ports:
      - 44600:8080
    depends_on:
      - db
    volumes:
      - ./backend/target:/app
    command: ["java", "-jar", "/app/app.jar"]

  db:
    container_name: db
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB


volumes:
  node_modules:
  db_data:
