services:
  frontend:
    container_name: frontend
    build: frontend
    ports:
      - 4200:4200
    depends_on:
      - backend
    volumes:
          - ./frontend/:/usr/src/app
          - node_modules:/usr/src/app/node_modules

  backend:
    container_name: backend
    build: backend
    ports:
      - 44600:8080
    depends_on:
      - db

  db:
    container_name: db
    build: db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB


volumes:
  node_modules:
  db_data:
